version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - alex-grover
    groups:
      dependencies:
        patterns:
          - '*'
