export const NAME = 'Alex Grover'
export const EMAIL = 'hello@alexgrover.me'
export const GITHUB_USERNAME = 'alex-grover'
export const INSTAGRAM_USERNAME = 'grovemau5'
export const LINKEDIN_USERNAME = 'alex-grover'
export const TWITTER_USERNAME = '@grovemau5'
