name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check code
        run: npm run check:code
      - name: Check types
        run: npm run check:types
      - name: Check formatting
        run: npm run check:format
      - name: Check styles
        run: npm run check:styles
